apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  labels: 
    app: front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        image: feltri08/front-scrum:latest
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: front-service
spec:
  type: NodePort
  selector:
    app: front
  ports:
  - port: 3000
    targetPort: 3000